shellEmulator: true

trustPolicy: no-downgrade

packages:
  - .

catalogs:
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@types/node': ^22.13.10
    bumpp: ^11.0.1
    eslint: ^10.2.1
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.21.10
    typescript: ^6.0.3
    vitest: ^3.2.4
  prod:
    '@clack/prompts': ^1.2.0
    cac: ^7.0.0
    consola: ^3.4.2
    ofetch: ^1.5.1
    picocolors: ^1.1.1
