// Library 入口 — 导出核心 API 供编程式使用
export { parseSourceUrl, sourceAddCommand } from '~/commands/source'
export { AGENTS, expandHome, getAgentById, getAgentsByIds } from '~/core/agents'
export { loadConfig, saveConfig } from '~/core/config'
export { installSkill } from '~/core/installer'
export type { InstallOptions, InstallResult } from '~/core/installer'
export { parseSkillMeta, scanGlobalSkills, scanLocalSkills } from '~/core/scanner'
export { uninstallSkill } from '~/core/uninstaller'
export type { UninstallOptions, UninstallResult } from '~/core/uninstaller'
export { collectUploadSkills, getUploadTarget, uploadSkills } from '~/core/upload'
export type { CollectUploadSkillsOptions, CollectUploadSkillsResult, UploadSkill, UploadSkillsOptions, UploadSkillsResult } from '~/core/upload'
export { createGitHubSource, parseGitHubUrl } from '~/sources/github'
export { createSkillsShSource, parseSkillsShSitemap, parseSkillsShUrl } from '~/sources/skills-sh'
export type { SkillSource } from '~/sources/types'
export type { AgentDefinition, InstalledSkill, InstallMode, SkillMeta, SkillsConfig, SkillSearchResult, SourceConfig, UploadConfig, UploadTargetConfig } from '~/types'
